sudo: false

language: ruby

rvm:
  - "1.9.3"

cache: bundler

before_install:
  - gem update bundler # Ensure we use the latest version of bundler. Travis' default version of outdated.

  # Run Elasticsearch as a daemon
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.13.zip
  - unzip elasticsearch-0.90.13.zip
  - elasticsearch-0.90.13/bin/elasticsearch

  # Run MongoDB as a daemon
  - curl -O https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.6.11.tgz
  - tar -zxf mongodb-linux-x86_64-2.6.11.tgz
  - export PATH=mongodb-linux-x86_64-2.6.11/bin:$PATH
  - mkdir -p ./mongo/db
  - mkdir -p ./mongo/log
  - mongod --fork --dbpath ./mongo/db --logpath ./mongo/log/mongodb.log

  #- gem install bundler
  #- wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.11.deb && sudo dpkg --force-confnew -i elasticsearch-0.90.11.deb && sudo service elasticsearch restart
  # Install mongo 2.6.4 according to http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/
  # TODO: This won't be necessary when travis switches to 2.6 by default - see https://github.com/travis-ci/travis-ci/issues/2246
  #- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  #- echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  #- sudo apt-get update -q
  #- sudo apt-get install -y mongodb-org=2.6.4 mongodb-org-server=2.6.4 mongodb-org-shell=2.6.4 mongodb-org-mongos=2.6.4 mongodb-org-tools=2.6.4
  #- mongo --version
script: bundle exec rspec
